### ISSUE TITLE
Monitor a validator on waiting list

### ISSUE THREAD

**Issue by HikaruG** [SimplyVC/panic_polkadot#21]
### Future support validator node functionalities for validator on waiting list 

Hello, I was wondering if I could monitor my node as a validator, even when it's on the waiting list.
Currently, as at the setup process the program checks the `get_eras_stakers`, it will fail when we put the stash account of a none active validator account. 

May I ask if there will be any support in the future for the functionalities of a validator node (current balance, current nominated stake, total stake etc) as a none active validator, or should we just put our node as monitoring node?

**Comment by dillu24** [comment]
Hi @HikaruG  thanks for your question.

It is possible to monitor a validator which is not in the active set yet, in fact we monitor ours. Can you give me the stash address of the validator so that I can replicate the issue?

With regards to balances, we currently monitor the bonded balance when the validator is active though. For the time being we will not be adding further functionalities as we are focusing on other high-priority tasks related to PANIC. That being said, these functionalities you have mentioned are planned to be included in the future.

**Comment by HikaruG** [comment]
@dillu24 Hello, thanks for your response! 
Here is my stash account: `5F21cD4mwgJLmc5GNaL3ooZtEin2mLJuku3rky5epWkbPCuJ`. 
It is a westend validator on the waiting list. 

But how can one replicate this issue, given that this stash account parameter needs to be set with the linked running instance which has its sessionKey set to the controller account (that the stash account has bonded too)? 

Understood for the priorities, thank you for answering my question !

**Comment by dillu24** [comment]
So I replicated the issue by connecting with a public node, and setting `stash_address` to be your stash. The problem is not because your validator is not in the active set, but because Westend does not have Democracy capabilities.

Essentially, for PANIC to monitor any chain, all functions in the Polkadot JS API must be supported. From what I can see, the democracy functions are not supported. In fact, when the council members function is called PANIC starts to error.

**Comment by HikaruG** [comment]
Oh ok that makes more sense.
I also ended up getting the`Undefined blockchain` error with the monitor node mode, which made me realize that the validator has not the only problem. 
Will try using my actual mainnet node, thank you for digging into the issue !

**Comment by dillu24** [comment]
Just to also to point out, that the Undefined blockchain error is also due that democracy blockchain metrics cannot be imported by the blockchain monitor because they do not exist for Westend.
